name: Debug

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'netclient version'
        required: true
  push:

jobs:

  version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Get Version Number
        id: version
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            NETCLIENT_VERSION=${{ github.event.inputs.version }}
          else
            NETCLIENT_VERSION=$(curl -fsSL https://api.github.com/repos/mattkasun/netclient/tags | grep 'name' | head -1 | cut -d'"' -f4)
          fi
          echo "version=${NETCLIENT_VERSION}" >> $GITHUB_OUTPUT
          # remove everything but digits and . for package (deb, rpm, etc) versions

          PACKAGE_VERSION=$(echo ${NETMAKER_VERSION} | tr -cd '[:digit:].')
          echo "tag=${PACKAGE_VERSION}" >> $GITHUB_OUTPUT
          echo GITHUB_OUTPUT.version
          echo GITHUB_OUTPUT.tag

  echo:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: echo
        run: |
          echo ${{ needs.version.outputs.version }}
          echo ${{ needs.version.outputs.tag }}
