# creates a PR from release branch to master
name: Create Release PR to master
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "netmaker version"
        required: true
  release:
    types: [released]

jobs:
  pr-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: create pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api --method POST \
          -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28'  \
          /repos/${{ github.repository }}/pulls \
          -f title='${{ github.event.inputs.version }}' \
          -f head='release_${{ github.event.inputs.version }}' \
          -f base="master"


