name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:
  release:
    uses: ${{ github.repository_owner }}/devops/.github/workflows/netclientRelease.yml@master
    with:
      version: ${{ inputs.version }}
    secrets: inherit
