name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true
      prerelease:
        description: "is this a prerelease"
        required: true
        type: boolean

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: create branch
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: setup git
        run: |
          git config user.name "Github Actions"
          git config user.emaail "info@netmaker.io"
      - name: fix go mod
        run: |
          go get github.com/gravitl/netmaker@${{ github.event.inputs.version }}
          go mod tidy
          if git tag --list | grep ${{ github.event.inputs.version }}; then
          git tag -d ${{ github.event.inputs.version }}
          fi
          git tag ${{ github.event.inputs.version }}
          git commit -am 'use netmaker@${{ github.event.inputs.version }}'
      - name: create release Branch
        run: |
          git switch -c release_${{ github.event.inputs.version }}
      - name: create pre-release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease}}



