name: Test Workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true
      prerelease:
        required: true
        type: boolean
        description: Is this a pre-release
  release:
    types: [published]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: vars
        run: |
          echo "ref" ${{ github.ref.name }}
          echo "event" ${{ github.event }}

