name: UpgradeRelease

on:
  workflow_dispatch:
    inputs:
      version:
        description: "release/version to update"
        required: true

jobs:

  update:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: release_${{ github.event.inputs.version }}
          fetch-depth: 0
      - run: |
          git fetch --force --tags
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean --release-notes release.md -f .goreleaser.update.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

  packages:
    uses: ./.github/workflows/packages.yml
    with:
      version: ${{ github.event.inputs.version }}

  pull-request:
    uses: ./.github/workflows/pull-request.yml
    with:
      version: ${{ github.event.inputs.version }}