name: UpgradeRelease

on:
  workflow_dispatch:
    inputs:
      version:
        description: "new version number"
        required: true

jobs:

  linux-headless:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: release_${{ github.event.inputs.version }}
          fetch-depth: 0
      - run: |
          git fetch --force --tags
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        
  freebsd-headless:
    runs-on: ubuntu-latest
    steps:
      - name: build freebsd
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: freebsd.clustercat.com
          username: freebsd
          key: ${{ secrets.TESTING_SSH_KEY }}
          script: |
            cd netclient
            git switch release_${{ github.event.inputs.version }}
            git restore .
            git pull
            go build -tags headless .
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/id_devops
          chmod 600 ~/.ssh/id_devops
          cat >>~/.ssh/config <<END
          Host *.clustercat.com
            User freebsd
            IdentityFile ~/.ssh/id_devops
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.TESTING_SSH_KEY }}
      - name: get freebsd binary
        run: |
          scp freebsd@freebsd.clustercat.com:~/netclient/netclient /tmp/
      - name: upload freebsd to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /tmp/netclient
          tag: ${{ github.event.inputs.version }}
          overwrite: true
          prerelease: true
          asset_name: netclient-freebsd-amd64
